version: "2.4"
services:
  prometheus:
     image: prom/prometheus:v2.22.0
     ports:
     - 9090:9090
     command:
     - --config.file=/etc/prometheus/prometheus.yml
     volumes:
     - /Users/pradip/csvserver/solution/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
     depends_on: 
      - csvserver

  csvserver:
     image: infracloudio/csvserver:latest
     ports:
     - 9393:9300
     environment:
     - CSVSERVER_BORDER= Orange
     volumes:
     - /Users/pradip/csvserver/solution/inputFile:/csvserver/inputdata
